import type { Config } from "./config";
import type { GitLabClient } from "./gitlab";
import type { GitOps } from "./git";
import { authedRepoUrl, branchName } from "./git";
import type { ClaudeResult, RunClaudeOptions } from "./claude";
import { jobLogger, type Logger } from "./log";
import type { Job } from "./queue";

export interface WorkerDeps {
  config: Config;
  gitlab: GitLabClient;
  git: GitOps;
  runClaude: (opts: RunClaudeOptions) => Promise<ClaudeResult>;
  logger: Logger;
}

/** MR / final comment body describing what Claude did. */
export function buildResultComment(mrUrl: string, result: ClaudeResult): string {
  const usage = result.usage
    ? ` (${result.usage.inputTokens ?? "?"} in / ${result.usage.outputTokens ?? "?"} out tokens)`
    : "";
  return [
    `✅ Opened a merge request: ${mrUrl}`,
    ``,
    result.summary.trim() || "_Claude did not provide a summary._",
    ``,
    `_Automated by the Claude agent${usage}._`,
  ].join("\n");
}

export function buildMrDescription(issueIid: number, result: ClaudeResult): string {
  return [
    result.summary.trim() || "_No summary provided._",
    ``,
    `Closes #${issueIid}`,
    ``,
    `---`,
    `_Generated by the Claude agent. Review before merging — CI, branch protection, and`,
    `approvals still apply; this service never merges anything itself._`,
  ].join("\n");
}

/** Create the per-job handler used by the queue. */
export function createWorker(deps: WorkerDeps) {
  const { config, gitlab, git, runClaude } = deps;

  return async function handle(job: Job): Promise<void> {
    const issue = job.payload;
    const log = jobLogger(deps.logger, job.id);
    log.info({ issue: issue.issueIid, project: issue.projectPath }, "job started");

    // a. acknowledge
    await gitlab
      .commentOnIssue(issue.projectId, issue.issueIid, "👋 On it — I'll open an MR shortly.")
      .catch((err) => log.warn({ err }, "could not post ack comment"));

    const repoUrl = authedRepoUrl(
      config.GITLAB_BASE_URL,
      issue.projectPath,
      config.BOT_GIT_USERNAME,
      config.GITLAB_BOT_TOKEN,
    );

    const branch = branchName(issue.issueIid, issue.title);
    let cleanup: (() => Promise<void>) | undefined;

    try {
      // b. prepare mirror + worktree
      await git.ensureMirror(repoUrl, issue.projectPath);
      const defaultBranch = await gitlab.defaultBranch(issue.projectId);
      const wt = await git.createWorktree(issue.projectPath, defaultBranch, branch);
      cleanup = wt.cleanup;

      // d. run Claude
      const result = await runClaude({
        worktreeDir: wt.dir,
        issue,
        maxTurns: config.MAX_TURNS,
        model: config.ANTHROPIC_MODEL,
        timeoutMs: config.JOB_TIMEOUT_MS,
        logger: log,
      });

      // e. commit + push if there are changes
      if (!(await git.hasChanges(wt.dir))) {
        log.info("no changes produced");
        await gitlab.commentOnIssue(
          issue.projectId,
          issue.issueIid,
          result.ok
            ? "🤔 I finished but produced no changes. The issue may need clarification."
            : `⚠️ The run did not complete cleanly and produced no changes.\n\n${result.summary.slice(0, 800)}`,
        );
        return;
      }

      await git.commitAll(wt.dir, `${issue.title}\n\nCloses #${issue.issueIid}`);
      await git.push(wt.dir, branch);

      // f. open MR
      const mr = await gitlab.createMergeRequest(issue.projectId, {
        sourceBranch: branch,
        targetBranch: defaultBranch,
        title: `Draft: ${issue.title}`,
        description: buildMrDescription(issue.issueIid, result),
      });

      // g. result comment
      await gitlab.commentOnIssue(
        issue.projectId,
        issue.issueIid,
        buildResultComment(mr.web_url, result),
      );
      log.info({ mr: mr.web_url }, "job completed");
    } catch (err) {
      log.error({ err }, "job failed");
      await gitlab
        .commentOnIssue(
          issue.projectId,
          issue.issueIid,
          `❌ Something went wrong while working on this issue. Check the service logs (job \`${job.id}\`).`,
        )
        .catch(() => undefined);
      throw err;
    } finally {
      if (cleanup) await cleanup().catch((err) => log.warn({ err }, "worktree cleanup failed"));
    }
  };
}
