import type { Config } from "./config";
import type { GitLabClient } from "./gitlab";
import type { GitOps } from "./git";
import { authedRepoUrl, branchName } from "./git";
import { buildPrompt, buildMrCommentPrompt, type ClaudeResult, type RunClaudeOptions } from "./claude";
import { jobLogger, type Logger } from "./log";
import type { Job } from "./queue";
import type { IssueJobPayload, MrCommentJobPayload } from "./webhook";

export interface WorkerDeps {
  config: Config;
  gitlab: GitLabClient;
  git: GitOps;
  runClaude: (opts: RunClaudeOptions) => Promise<ClaudeResult>;
  logger: Logger;
}

function usageSuffix(result: ClaudeResult): string {
  return result.usage
    ? ` (${result.usage.inputTokens ?? "?"} in / ${result.usage.outputTokens ?? "?"} out tokens)`
    : "";
}

/** Issue result comment (links the opened MR). */
export function buildResultComment(mrUrl: string, result: ClaudeResult): string {
  return [
    `✅ Opened a merge request: ${mrUrl}`,
    ``,
    result.summary.trim() || "_Claude did not provide a summary._",
    ``,
    `_Automated by the Claude agent${usageSuffix(result)}._`,
  ].join("\n");
}

export function buildMrDescription(issueIid: number, result: ClaudeResult): string {
  return [
    result.summary.trim() || "_No summary provided._",
    ``,
    `Closes #${issueIid}`,
    ``,
    `---`,
    `_Generated by the Claude agent. Review before merging — CI, branch protection, and`,
    `approvals still apply; this service never merges anything itself._`,
  ].join("\n");
}

/** Reply posted on the MR after iterating on a comment. */
export function buildMrReplyComment(result: ClaudeResult, pushed: boolean): string {
  const head = pushed
    ? "✅ Pushed changes to this MR's branch."
    : "🤔 I looked into it but didn't make any changes.";
  return [
    head,
    ``,
    result.summary.trim() || "_Claude did not provide a summary._",
    ``,
    `_Automated by the Claude agent${usageSuffix(result)}._`,
  ].join("\n");
}

/** Create the per-job handler used by the queue. */
export function createWorker(deps: WorkerDeps) {
  return async function handle(job: Job): Promise<void> {
    const log = jobLogger(deps.logger, job.id);
    if (job.payload.kind === "mr_comment") {
      return handleMrComment(deps, job, job.payload, log);
    }
    return handleIssue(deps, job, job.payload, log);
  };
}

async function handleIssue(
  deps: WorkerDeps,
  job: Job,
  issue: IssueJobPayload,
  log: Logger,
): Promise<void> {
  const { config, gitlab, git, runClaude } = deps;
  log.info({ issue: issue.issueIid, project: issue.projectPath }, "issue job started");

  await gitlab
    .commentOnIssue(issue.projectId, issue.issueIid, "👋 On it — I'll open an MR shortly.")
    .catch((err) => log.warn({ err }, "could not post ack comment"));

  const repoUrl = authedRepoUrl(
    config.GITLAB_BASE_URL,
    issue.projectPath,
    config.BOT_GIT_USERNAME,
    config.GITLAB_BOT_TOKEN,
  );
  const branch = branchName(issue.issueIid, issue.title);
  let cleanup: (() => Promise<void>) | undefined;

  try {
    await git.ensureMirror(repoUrl, issue.projectPath);
    const defaultBranch = await gitlab.defaultBranch(issue.projectId);
    const wt = await git.createWorktree(issue.projectPath, defaultBranch, branch);
    cleanup = wt.cleanup;

    const result = await runClaude({
      worktreeDir: wt.dir,
      prompt: buildPrompt(issue),
      maxTurns: config.MAX_TURNS,
      model: config.ANTHROPIC_MODEL,
      timeoutMs: config.JOB_TIMEOUT_MS,
      logger: log,
    });

    if (!(await git.hasChanges(wt.dir))) {
      log.info("no changes produced");
      await gitlab.commentOnIssue(
        issue.projectId,
        issue.issueIid,
        result.ok
          ? "🤔 I finished but produced no changes. The issue may need clarification."
          : `⚠️ The run did not complete cleanly and produced no changes.\n\n${result.summary.slice(0, 800)}`,
      );
      return;
    }

    await git.commitAll(wt.dir, `${issue.title}\n\nCloses #${issue.issueIid}`);
    await git.push(wt.dir, branch);

    const mr = await gitlab.createMergeRequest(issue.projectId, {
      sourceBranch: branch,
      targetBranch: defaultBranch,
      title: `Draft: ${issue.title}`,
      description: buildMrDescription(issue.issueIid, result),
    });

    await gitlab.commentOnIssue(
      issue.projectId,
      issue.issueIid,
      buildResultComment(mr.web_url, result),
    );
    log.info({ mr: mr.web_url }, "issue job completed");
  } catch (err) {
    log.error({ err }, "issue job failed");
    await gitlab
      .commentOnIssue(
        issue.projectId,
        issue.issueIid,
        `❌ Something went wrong while working on this issue. Check the service logs (job \`${job.id}\`).`,
      )
      .catch(() => undefined);
    throw err;
  } finally {
    if (cleanup) await cleanup().catch((err) => log.warn({ err }, "worktree cleanup failed"));
  }
}

async function handleMrComment(
  deps: WorkerDeps,
  job: Job,
  mr: MrCommentJobPayload,
  log: Logger,
): Promise<void> {
  const { config, gitlab, git, runClaude } = deps;
  log.info({ mr: mr.mrIid, project: mr.projectPath, branch: mr.sourceBranch }, "mr comment job started");

  await gitlab
    .commentOnMergeRequest(mr.projectId, mr.mrIid, "👋 On it — I'll push an update shortly.")
    .catch((err) => log.warn({ err }, "could not post ack comment"));

  const repoUrl = authedRepoUrl(
    config.GITLAB_BASE_URL,
    mr.projectPath,
    config.BOT_GIT_USERNAME,
    config.GITLAB_BOT_TOKEN,
  );
  let cleanup: (() => Promise<void>) | undefined;

  try {
    await git.ensureMirror(repoUrl, mr.projectPath);
    // Check out the MR's own branch so commits land on it.
    const wt = await git.createWorktreeFromExisting(mr.projectPath, mr.sourceBranch);
    cleanup = wt.cleanup;

    const result = await runClaude({
      worktreeDir: wt.dir,
      prompt: buildMrCommentPrompt(mr),
      maxTurns: config.MAX_TURNS,
      model: config.ANTHROPIC_MODEL,
      timeoutMs: config.JOB_TIMEOUT_MS,
      logger: log,
    });

    const pushed = await git.hasChanges(wt.dir);
    if (pushed) {
      await git.commitAll(wt.dir, `Address review comment on !${mr.mrIid}`);
      await git.push(wt.dir, mr.sourceBranch);
    }

    await gitlab.commentOnMergeRequest(mr.projectId, mr.mrIid, buildMrReplyComment(result, pushed));
    log.info({ mr: mr.mrIid, pushed }, "mr comment job completed");
  } catch (err) {
    log.error({ err }, "mr comment job failed");
    await gitlab
      .commentOnMergeRequest(
        mr.projectId,
        mr.mrIid,
        `❌ Something went wrong while addressing that comment. Check the service logs (job \`${job.id}\`).`,
      )
      .catch(() => undefined);
    throw err;
  } finally {
    if (cleanup) await cleanup().catch((err) => log.warn({ err }, "worktree cleanup failed"));
  }
}
